[{"id":615854510,"node_id":"R_kgDOJLUxrg","name":"exploit-CVE-2020-24815.py","full_name":"ziadanbari2021/exploit-CVE-2020-24815.py","private":false,"owner":{"login":"ziadanbari2021","id":111196316,"node_id":"U_kgDOBqC4nA","avatar_url":"https://avatars.githubusercontent.com/u/111196316?v=4","url":"https://api.github.com/users/ziadanbari2021","html_url":"https://github.com/ziadanbari2021","type":"User","site_admin":false},"html_url":"https://github.com/ziadanbari2021/exploit-CVE-2020-24815.py","description":"","fork":false,"url":"https://api.github.com/repos/ziadanbari2021/exploit-CVE-2020-24815.py","created_at":"2023-03-18T21:42:29Z","updated_at":"2023-03-18T21:46:31Z","pushed_at":"2023-03-18T22:49:49Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":0,"default_branch":"main","score":1}]